language:
- scala
scala:
- 2.13.1
branches: 
only:
- master
before_install:
- nvm install node
- node --version
- npm --version
install:
- npm install -g serverless
script:
- sbt assembly
after_script:
- serverless deploy --verbose
env:
  global:
  - secure: qArbX05aWAY24Iy8SemrNTJT34Yg+FD2U6fCvpbKYlDuZmfwNlbhUmhir9IJHp+opLagarbu5hsYz4Nhq7Y5VZAY6/p90nMp6Qd4W9NQOLJQSUxUH8pWeOH/zPTrNRXseTEr184dize9QhhhxcmkmC7Hg9ws/i38BmSaV5RMubnbTWTJh6u3X71rvSy9ms4JpOapt/T9qbK3ceBr6ier+CJvglbSqgHsp3+ZsE8Uejh0SVC3LEbS1FEju0FNRqMJEIRGTAUS28XRYZHQGMc8eKa4m0AKPYUyTnut87tBYAIZpOqHAN6xm9ZvALRzsttbXatimgVsEeW6m8Klgf0FmZ+wYLeOAre93pilRjc1V2LaSstU/iSoTqwus9JoyYlw5cZhs+lbMoIbTBjCK5DKOeNLY89WZOvJX8Q2bNPN4O8c5Am+Z+0foTK46Ccf9JZ3YhTHIM0+R87KQzQU49mNDsEfBbXovtU2y1iT6cnN9n+1oPgMVSByt31L70Ye1/2fLYPm+i0dN+eiYKCvSVwSgTokdDyB+WmexZ8B6xRpD6VDdgzrK0kFvq5lAgnDFvvYHnFnSbIwkpFDgCfS+ZmWnowubrSjesnGyDq/upMZckImPOPdLEUhpz3XJQPT5OYkDB+vre1RsYrBgwkOt6+PgUZ6tw6tNwRs2ATca4lJkcQ=
  - secure: YI0f8TJQB/EcWV5HtxYz0v9SR9/6dn+LXtDdn2Nhz7ckj6fzszqosqcCmdPBA5tZaflG0dcE1chjGbHooVlgNPQAEE5z+rguoppqcA32vfLi+/N5LPCqOUIOCtZGgn5O3OJ+SaMtQeLk8KzdLBhTQhQlPP+pOPrwDj9J2GWoWoGix8AHhfm5XIvQitasG1MjAXvpy5XfdsfKal4FlLbszcx2VBe5NWAsfR/Mcng130Nfn074r+Vzi2i656FWZ52NKLN8HcbY9SgV018CEH390NjtFlQAk++cCqAOumjth3AAksNyJgWQexBS4P6UuhdeGLsRCyvWPwvRhRDOHpQYHay8l5sYQxd6OIuct3UDxK6uKfKWYuN7zvpaddYWC2Zbg5j1U/ppiQZfm5u50AaisyqanJhmbu3q48+Dlc+0PYB7lRa5gTWnR+UKuJCBLk+Mdmpmb06Nv9webdvFkiRFgBnufsloLGAVuOf/LNNxvbpjIfQH62u6ovhwhH/uc8/ggS5nfDf1Cq5MdaI2mGnfMTTGW+l3/NpozQanPmbUZxft6Muo5yn8Qp0kZV2bIUovAp/JSKkVch9b6hCVaeUpjmau2pmSRZ+n/s9AFT0VQHMHRHxEKQr3tUVf9PwiqAeyPiefFygkrnNSANJi33L/bSYBUrbsLW4SlOCFwpE6ndo=
