language:
  - scala
# jdk:
#   - openjdk8
scala:
  - 2.13.1
# branches:
# only:
#   - master
# before_install:
#   - nvm install 6
#   - node --version
#   - npm --version
# install:
#   - npm install -g serverless
# script:
#   - sbt assembly
# after_script:
#   - serverless deploy -v